Acknowledgments
===============

2016 - 2017
-----------

.. note::

    **#TODO Add Acknowledgement for LBL Kavli project and acknowledge other projects as well**

2015 - 2016
-----------

The Neurodata Without Borders: Neurophysiology Initiative is funded by
GE, the Allen Institute for Brain Science, the Howard Hughes Medical
Institute (HHMI), The Kavli Foundation and the International
Neuroinformatics Coordinating Facility. Our founding scientific partners
are the Allen Institute, the Svoboda Lab at the Janelia Research Campus
of HHMI, the Meister Lab at the California Institute of Technology, the
Buzsaki Lab at New York University School of Medicine, and the
University of California, Berkeley. Ovation.io is our founding
development partner. Ken Harris at University College London provided
invaluable input and advice.