.. _nwb-type-namespace-doc:

Namespace: NWB core
===================

- **Description:** NWB namespace
- **Name:** core
- **Full Name:** NWB core
- **Version:** 1.2.0
- **Authors:**
    - Keith Godfrey
    - Jeff Teeters
    - Oliver Ruebel
    - Andrew Tritt

- **Contacts:**
    - keithg@alleninstitute.org
    - jteeters@berkeley.edu
    - oruebel@lbl.gov
    - ajtritt@lbl.gov

- **Schema:**
    - **source:** nwb.base.yaml 
    - **source:** nwb.epoch.yaml 
    - **source:** nwb.image.yaml 
    - **source:** nwb.file.yaml 
    - **source:** nwb.misc.yaml 
    - **source:** nwb.behavior.yaml 
    - **source:** nwb.ecephys.yaml 
    - **source:** nwb.icephys.yaml 
    - **source:** nwb.ogen.yaml 
    - **source:** nwb.ophys.yaml 
    - **source:** nwb.retinotopy.yaml 


.. only:: html 

    .. include:: _format_auto_docs/format_spec_type_hierarchy.inc

