.. _sec-Device-src:

Device
^^^^^^

**Extends:** :ref:`NWBContainer <sec-NWBContainer>`

**Description:** see :numref:`sec-Device`

**YAML Specification:**

.. code-block:: yaml
    :linenos:

    attributes:
    - doc: Value is 'A recording device e.g. amplifier'
      dtype: str
      name: help
      value: A recording device e.g. amplifier
    doc: One of possibly many. Information about device and device description.
    neurodata_type_def: Device
    neurodata_type_inc: NWBContainer


