.. _neurodata_type_hierarchy:

Type Hierarchy
--------------

* :ref:`Image <sec-Image>`
* :ref:`NWBContainer <sec-NWBContainer>`

   * :ref:`BehavioralEpochs <sec-BehavioralEpochs>`
   * :ref:`BehavioralEvents <sec-BehavioralEvents>`
   * :ref:`BehavioralTimeSeries <sec-BehavioralTimeSeries>`
   * :ref:`ClusterWaveforms <sec-ClusterWaveforms>`
   * :ref:`Clustering <sec-Clustering>`
   * :ref:`CompassDirection <sec-CompassDirection>`
   * :ref:`CorrectedImageStack <sec-CorrectedImageStack>`
   * :ref:`Device <sec-Device>`
   * :ref:`DfOverF <sec-DfOverF>`
   * :ref:`ElectrodeGroup <sec-ElectrodeGroup>`
   * :ref:`Epoch <sec-Epoch>`
   * :ref:`EpochTimeSeries <sec-EpochTimeSeries>`
   * :ref:`EventDetection <sec-EventDetection>`
   * :ref:`EventWaveform <sec-EventWaveform>`
   * :ref:`EyeTracking <sec-EyeTracking>`
   * :ref:`FeatureExtraction <sec-FeatureExtraction>`
   * :ref:`FilteredEphys <sec-FilteredEphys>`
   * :ref:`Fluorescence <sec-Fluorescence>`
   * :ref:`ImageSegmentation <sec-ImageSegmentation>`
   * :ref:`ImagingPlane <sec-ImagingPlane>`
   * :ref:`ImagingRetinotopy <sec-ImagingRetinotopy>`
   * :ref:`IntracellularElectrode <sec-IntracellularElectrode>`
   * :ref:`LFP <sec-LFP>`
   * :ref:`MotionCorrection <sec-MotionCorrection>`
   * :ref:`NWBFile <sec-NWBFile>`
   * :ref:`OpticalChannel <sec-OpticalChannel>`
   * :ref:`OptogeneticStimulusSite <sec-OptogeneticStimulusSite>`
   * :ref:`PlaneSegmentation <sec-PlaneSegmentation>`
   * :ref:`Position <sec-Position>`
   * :ref:`ProcessingModule <sec-ProcessingModule>`
   * :ref:`PupilTracking <sec-PupilTracking>`
   * :ref:`ROI <sec-ROI>`
   * :ref:`SpikeUnit <sec-SpikeUnit>`
   * :ref:`TimeSeries <sec-TimeSeries>`

      * :ref:`AbstractFeatureSeries <sec-AbstractFeatureSeries>`
      * :ref:`AnnotationSeries <sec-AnnotationSeries>`
      * :ref:`ElectricalSeries <sec-ElectricalSeries>`

         * :ref:`SpikeEventSeries <sec-SpikeEventSeries>`
      * :ref:`ImageSeries <sec-ImageSeries>`

         * :ref:`ImageMaskSeries <sec-ImageMaskSeries>`
         * :ref:`OpticalSeries <sec-OpticalSeries>`
         * :ref:`TwoPhotonSeries <sec-TwoPhotonSeries>`
      * :ref:`IndexSeries <sec-IndexSeries>`
      * :ref:`IntervalSeries <sec-IntervalSeries>`
      * :ref:`OptogeneticSeries <sec-OptogeneticSeries>`
      * :ref:`PatchClampSeries <sec-PatchClampSeries>`

         * :ref:`CurrentClampSeries <sec-CurrentClampSeries>`

            * :ref:`IZeroClampSeries <sec-IZeroClampSeries>`
         * :ref:`CurrentClampStimulusSeries <sec-CurrentClampStimulusSeries>`
         * :ref:`VoltageClampSeries <sec-VoltageClampSeries>`
         * :ref:`VoltageClampStimulusSeries <sec-VoltageClampStimulusSeries>`
      * :ref:`RoiResponseSeries <sec-RoiResponseSeries>`
      * :ref:`SpatialSeries <sec-SpatialSeries>`
   * :ref:`UnitTimes <sec-UnitTimes>`
* :ref:`SpecFile <sec-SpecFile>`


