.. include:: _format_auto_docs/core_namespace_description.inc

.. raw:: latex

    \clearpage \newpage

.. _nwb-type-specifications:

Specifications
==============

Main Data File
--------------

.. include:: _format_auto_docs/NWBFile_description.inc

.. raw:: latex

    \clearpage \newpage


.. raw:: latex

    \clearpage \newpage

TimeSeries Types
----------------

.. include:: _format_auto_docs/TimeSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/AbstractFeatureSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/AnnotationSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ElectricalSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/SpikeEventSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImageSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImageMaskSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/OpticalSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/TwoPhotonSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/IndexSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/IntervalSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/OptogeneticSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/PatchClampSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/CurrentClampSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/IZeroClampSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/CurrentClampStimulusSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/VoltageClampSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/VoltageClampStimulusSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/RoiResponseSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/SpatialSeries_description.inc

.. raw:: latex

    \clearpage \newpage


.. raw:: latex

    \clearpage \newpage

Data Processing
---------------

.. include:: _format_auto_docs/ProcessingModule_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/BehavioralEpochs_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/BehavioralEvents_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/BehavioralTimeSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ClusterWaveforms_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Clustering_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/CompassDirection_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/CorrectedImageStack_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/DfOverF_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/EpochTimeSeries_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/EventDetection_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/EventWaveform_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/EyeTracking_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/FeatureExtraction_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/FilteredEphys_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Fluorescence_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImageSegmentation_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImagingPlane_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImagingRetinotopy_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/IntracellularElectrode_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/LFP_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/MotionCorrection_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/OpticalChannel_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/OptogeneticStimulusSite_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/PlaneSegmentation_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Position_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/PupilTracking_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ROI_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/SpikeUnit_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/UnitTimes_description.inc

.. raw:: latex

    \clearpage \newpage


.. raw:: latex

    \clearpage \newpage

Other Types
-----------

.. include:: _format_auto_docs/ElectrodeGroup_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Device_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Epoch_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/SpecFile_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Image_description.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/NWBContainer_description.inc

.. raw:: latex

    \clearpage \newpage

