.. _nwb-type-specification-sources:

Sources
=======

.. include:: _format_auto_docs/core_namespace_source.inc
.. _Main_Data_File_src:

Main Data File
--------------

.. include:: _format_auto_docs/NWBFile_source.inc

.. raw:: latex

    \clearpage \newpage

.. _TimeSeries_Types_src:

TimeSeries Types
----------------

.. include:: _format_auto_docs/TimeSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/AbstractFeatureSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/AnnotationSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ElectricalSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/SpikeEventSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImageSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImageMaskSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/OpticalSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/TwoPhotonSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/IndexSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/IntervalSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/OptogeneticSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/PatchClampSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/CurrentClampSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/IZeroClampSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/CurrentClampStimulusSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/VoltageClampSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/VoltageClampStimulusSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/RoiResponseSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/SpatialSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. _Data_Processing_src:

Data Processing
---------------

.. include:: _format_auto_docs/ProcessingModule_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/BehavioralEpochs_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/BehavioralEvents_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/BehavioralTimeSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ClusterWaveforms_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Clustering_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/CompassDirection_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/CorrectedImageStack_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/DfOverF_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/EpochTimeSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/EventDetection_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/EventWaveform_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/EyeTracking_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/FeatureExtraction_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/FilteredEphys_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Fluorescence_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImageSegmentation_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImagingPlane_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ImagingRetinotopy_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/IntracellularElectrode_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/LFP_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/MotionCorrection_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/OpticalChannel_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/OptogeneticStimulusSite_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/PlaneSegmentation_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Position_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/PupilTracking_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/ROI_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/SpikeUnit_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/UnitTimes_source.inc

.. raw:: latex

    \clearpage \newpage

.. _Other_Types_src:

Other Types
-----------

.. include:: _format_auto_docs/ElectrodeGroup_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/SpecFile_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Epoch_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/NWBContainer_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Device_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: _format_auto_docs/Image_source.inc

.. raw:: latex

    \clearpage \newpage

