.. _sec-Interface:

Interface
^^^^^^^^^

**Source Specification:** see :numref:`sec-Interface-src`

**Overview:** The attributes specified here are included in all interfaces.




.. figure:: ./_format_auto_docs/Interface.*
    :alt: Interface




.. tabularcolumns:: |p{4cm}|p{1cm}|p{10cm}|
.. _table-Interface-data:

.. table:: Datasets, Links, and Attributes contained in <Interface>
    :class: longtable

    +---------------+-------------+-----------------------------------------------------------------+
    | Id            | Type        | Description                                                     |
    +===============+=============+=================================================================+
    | <Interface>   | group       | Top level group for <Interface>                                 |
    +---------------+-------------+-----------------------------------------------------------------+
    | .source       | attribute   | Path to the origin of the data represented in this interface.   |
    |               |             |                                                                 |
    |               |             | - **Data Type:** text                                           |
    |               |             |                                                                 |
    +---------------+-------------+-----------------------------------------------------------------+
    | .help         | attribute   | Short description of what this type of Interface contains.      |
    |               |             |                                                                 |
    |               |             | - **Data Type:** text                                           |
    |               |             |                                                                 |
    +---------------+-------------+-----------------------------------------------------------------+



