.. _sec-Interface-src:

Interface
^^^^^^^^^

**Description:** see :numref:`sec-Interface`

**YAML Specification:**

.. code-block:: yaml
    :linenos:

    attributes:
    - doc: Path to the origin of the data represented in this interface.
      dtype: text
      name: source
    - doc: Short description of what this type of Interface contains.
      dtype: text
      name: help
    doc: The attributes specified here are included in all interfaces.
    neurodata_type_def: Interface


