Type Overview
=============

.. include:: format_auto_docs/format_spec_type_hierarchy.inc

.. raw:: latex

    \clearpage \newpage

Format Specification
====================

.. include:: format_auto_docs/AbstractFeatureSeries_description.inc
.. include:: format_auto_docs/AbstractFeatureSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/AnnotationSeries_description.inc
.. include:: format_auto_docs/AnnotationSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/BehavioralEpochs_description.inc
.. include:: format_auto_docs/BehavioralEpochs_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/BehavioralEvents_description.inc
.. include:: format_auto_docs/BehavioralEvents_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/BehavioralTimeSeries_description.inc
.. include:: format_auto_docs/BehavioralTimeSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ClusterWaveforms_description.inc
.. include:: format_auto_docs/ClusterWaveforms_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/Clustering_description.inc
.. include:: format_auto_docs/Clustering_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/CompassDirection_description.inc
.. include:: format_auto_docs/CompassDirection_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/CorrectedImageStack_description.inc
.. include:: format_auto_docs/CorrectedImageStack_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/CurrentClampSeries_description.inc
.. include:: format_auto_docs/CurrentClampSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/CurrentClampStimulusSeries_description.inc
.. include:: format_auto_docs/CurrentClampStimulusSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/Device_description.inc
.. include:: format_auto_docs/Device_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/DfOverF_description.inc
.. include:: format_auto_docs/DfOverF_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ElectricalSeries_description.inc
.. include:: format_auto_docs/ElectricalSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ElectrodeGroup_description.inc
.. include:: format_auto_docs/ElectrodeGroup_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/Epoch_description.inc
.. include:: format_auto_docs/Epoch_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/EpochTimeSeries_description.inc
.. include:: format_auto_docs/EpochTimeSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/EventDetection_description.inc
.. include:: format_auto_docs/EventDetection_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/EventWaveform_description.inc
.. include:: format_auto_docs/EventWaveform_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/EyeTracking_description.inc
.. include:: format_auto_docs/EyeTracking_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/FeatureExtraction_description.inc
.. include:: format_auto_docs/FeatureExtraction_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/FilteredEphys_description.inc
.. include:: format_auto_docs/FilteredEphys_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/Fluorescence_description.inc
.. include:: format_auto_docs/Fluorescence_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/IZeroClampSeries_description.inc
.. include:: format_auto_docs/IZeroClampSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/Image_description.inc
.. include:: format_auto_docs/Image_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ImageMaskSeries_description.inc
.. include:: format_auto_docs/ImageMaskSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ImageSegmentation_description.inc
.. include:: format_auto_docs/ImageSegmentation_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ImageSeries_description.inc
.. include:: format_auto_docs/ImageSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ImagingPlane_description.inc
.. include:: format_auto_docs/ImagingPlane_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ImagingRetinotopy_description.inc
.. include:: format_auto_docs/ImagingRetinotopy_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/IndexSeries_description.inc
.. include:: format_auto_docs/IndexSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/Interface_description.inc
.. include:: format_auto_docs/Interface_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/IntervalSeries_description.inc
.. include:: format_auto_docs/IntervalSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/IntracellularElectrode_description.inc
.. include:: format_auto_docs/IntracellularElectrode_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/LFP_description.inc
.. include:: format_auto_docs/LFP_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/Module_description.inc
.. include:: format_auto_docs/Module_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/MotionCorrection_description.inc
.. include:: format_auto_docs/MotionCorrection_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/NWBFile_description.inc
.. include:: format_auto_docs/NWBFile_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/OpticalChannel_description.inc
.. include:: format_auto_docs/OpticalChannel_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/OpticalSeries_description.inc
.. include:: format_auto_docs/OpticalSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/OptogeneticSeries_description.inc
.. include:: format_auto_docs/OptogeneticSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/OptogeneticStimulusSite_description.inc
.. include:: format_auto_docs/OptogeneticStimulusSite_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/PatchClampSeries_description.inc
.. include:: format_auto_docs/PatchClampSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/PlaneSegmentation_description.inc
.. include:: format_auto_docs/PlaneSegmentation_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/Position_description.inc
.. include:: format_auto_docs/Position_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/PupilTracking_description.inc
.. include:: format_auto_docs/PupilTracking_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/ROI_description.inc
.. include:: format_auto_docs/ROI_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/RoiResponseSeries_description.inc
.. include:: format_auto_docs/RoiResponseSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/SpatialSeries_description.inc
.. include:: format_auto_docs/SpatialSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/SpecFile_description.inc
.. include:: format_auto_docs/SpecFile_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/SpikeEventSeries_description.inc
.. include:: format_auto_docs/SpikeEventSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/SpikeUnit_description.inc
.. include:: format_auto_docs/SpikeUnit_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/TimeSeries_description.inc
.. include:: format_auto_docs/TimeSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/TwoPhotonSeries_description.inc
.. include:: format_auto_docs/TwoPhotonSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/UnitTimes_description.inc
.. include:: format_auto_docs/UnitTimes_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/VoltageClampSeries_description.inc
.. include:: format_auto_docs/VoltageClampSeries_source.inc

.. raw:: latex

    \clearpage \newpage

.. include:: format_auto_docs/VoltageClampStimulusSeries_description.inc
.. include:: format_auto_docs/VoltageClampStimulusSeries_source.inc

.. raw:: latex

    \clearpage \newpage

