name: Validate schema

on: [push, pull_request_target]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install hdmf
      run: |
        pip install git+https://github.com/hdmf-dev/hdmf.git
    - name: Validate schema specification
      run: |
        validate_hdmf_spec core -m nwb.schema.json
